### ISSUE TITLE
Produce "annotation" emit

### ISSUE THREAD

**Issue by alexeagle** [angular/tsickle#131] opened 2016-04-18 22:49 UTC
The TS Decorator emit doesn't tree-shake with closure compiler.

With Sickle@head, a typical decorated class looks like
```
let PercentPipe = class extends NumberPipe {
    /**
     * @param {?} value
     * @param {?} args
     * @return {?}
     */
    transform(value, args) {
        var /** @type {?} */ digits = collection_1.ListWrapper.first(args);
        return NumberPipe._format(value, intl_1.NumberFormatStyle.Percent, digits);
    }
};
PercentPipe = __decorate([
    lang_1.CONST(),
    core_1.Pipe({ name: 'percent' }),
    core_1.Injectable(),
    __metadata('design:paramtypes', [])
], PercentPipe);
exports.PercentPipe = PercentPipe;
```

Closure cannot remove this class from the output, because
- `__decorate` loses the type of the original declared class
- Decorators can modify the declaration of the class in a way that allows runtime references to the class
- decorator metadata (`--emitDecoratorMetadata`) is stored in a global variable and references all decorated classes.

This causes angular2 to be something like 40% larger than it should be.

## Proposal

Mark some decorators as "require annotation semantics". In these semantics, the decorator cannot modify the class declaration or retain references, it can only patch additional properties on the function representing the type.

When sickle encounters one of these decorators, it should do its own lowering to a syntax @tbosch  will describe...

**Comment by tbosch** [comment] 2016-04-18 23:00
The lowering should be something like this:
```
class PercentPipe extends NumberPipe {
  constructor(@Inject(Z) x: Y) {}
}
// annotations
PercentPipe.annotations = [
    lang_1.CONST(),
    core_1.Pipe({ name: 'percent' }),
    core_1.Injectable(),
];
// constructor arguments (one entry per argument)
PercentPipe.parameters = [[core_1.Inject(Z), Y], ...];
```

**Comment by tbosch** [comment] 2016-04-18 23:00
For now we could just say we always use these semantics in G3 for decorators, without a configuration.

**Comment by martine** [comment] 2016-04-18 23:02
This is getting pretty far away from the syntax/semantics of decorators.  Would it make sense to have a pass within angular's build that translates from its @foo stuff into the desired TypeScript?  (Another way of saying this is: doesn't this transformation belong within angular, given that it's not a TS or Closure problem?)  Honest question, not just telling you to go away.  :)

**Comment by alexeagle** [comment] 2016-04-18 23:09
It's not only the angular framework, but also any third-party components (like all of material2) that would need to de-sugar their decorators this way.
It's a TS problem, insofar as we want to have an Annotations language feature instead of Decorators, and other similar usages would want it too.
We could do the transformation somewhere else, but it would look almost identical to sickle, just run under different circumstances?

**Comment by tbosch** [comment] 2016-04-19 00:52
The problem is that the spec for decorators prevents tree shaking in
general. I.e. this is a spec problem of decorators in general.

**Comment by martine** [comment] 2016-04-25 22:50
Can you give me an example of what the source looks like (before TypeScript emits?).

What should happen to .parameters if the class doesn't have a constructor?

Does this need to happen separately from all the other sickle stuff?  (I.e. do you need a program that can do this without doing all the other Closure conversion goop?)

**Comment by alexeagle** [comment] 2016-04-25 23:25
PercentPipe is defined here
https://github.com/angular/angular/blob/67d05eb65fa5e8436625d6a0baacd774470fe6ed/modules/angular2/src/common/pipes/number_pipe.ts#L113

It should be a separate API call from `annotate`, indeed we don't need to do any of the present closure behavior for the angular use case. But tsc_wrapped will eventually need to do the same decorator lowering since all google3 TS code is affected by the non-tree-shakability of Decorators.

**Comment by martine** [comment] 2016-04-25 23:28
OK, so it looks like I transform
1) all class-level decorators into a static prop with calls to those decorators
2) all ctor-level decorators into another static prop?  Or only the @Inject ctor decorators? 
@tbosch

**Comment by martine** [comment] 2016-04-26 00:17
Did the class transformation here, PTAL at the test case and let me know if it looks like what you're expecting.
https://reviews.angular.io/D84

**Comment by martine** [comment] 2016-04-26 00:23
@tbosch you wrote:
```js
PercentPipe.parameters = [[core_1.Inject(Z), Y], ...];
```

But `Y` is a type in your example.  What did you mean here?

**Comment by tbosch** [comment] 2016-04-26 01:06
We need to capture all ctor argument types as well, even without Angular's `@Inject` annotation.

The `Y` in the example is the type of the parameter, which we need to capture as well. We represent both the parameter annotation as well as the parameter type in an array for simplicity (there can be n parameter annotations and 1 parameter type in it).

**Comment by martine** [comment] 2016-04-26 01:28
You can't put a type in an array, they are different kinds of things.

If you had `constructor(@Inject(Z) x: number) {}`, I can't put `number` in an array.
I think I'm missing something.  :)

**Comment by martine** [comment] 2016-04-26 01:31
Could you give examples of what you'd like in the cases of:

1) no constructor
2) no constructor, but the superclass has a constructor
3) `constructor(x: number) {}`
4) `constructor(@Inject(Z) x: number) {}`

**Comment by tbosch** [comment] 2016-04-26 02:20
Yes, you are right, many types don't have direct representation (like `any`).
However, what we care about most are types that are references to classes. With that we can calculate dependencies for DI during runtime.

E.g.
```
class PercentPipe {
  constructor(public config: PercentPipeConfig) {}
}
```
Here we would need to get
```
PrecentPipe.parameters = [[PercentPipeConfig]];
```

Combined with `@Inject`:
```
class PercentPipe {
  constructor(public @Inject(MySpecialConfig) config: PercentPipeConfig) {}
}
```
would result in
```
PrecentPipe.parameters = [[PercentPipeConfig, Inject(MySpecialConfig)]];
```

For the other cases you mentioned:
1) `[]`
2) In TypeScript, constructors are inherited. So I would expect to get the same parameters as the superclass.
3) `[]`
4) `[Inject(Z)]`

**Comment by tbosch** [comment] 2016-04-26 02:31
There is an open point in this proposal though: How to get from a decorator function to an annotation class. Decorators are functions that return functions with the signature `(Type) => Type`. I.e. we can't just call them to create data.

I.e. if a user writes
```
import {Injectable} from 'angular/core';

@Component({template: 'someClass.html'})
class SomeClass {}
```

Then we can't just convert this into
```
class SomeClass {}
SomeClass.annotations = [Component({template: 'someClass.html'})]
```

Rather, let's do the following (similar to constructor parameters):
```
class SomeClass {}
SomeClass.annotations = [{
  decorator: Component,
  args: [{
    template: 'someClass.html'
  }]
}]
```

With this, we would have no top level function calls at all, and there would be a defined mapping for each decorator to annotation data. Even better, if somebody needs to, he can execute the decorator later in time as all data to do so is preserved.

@mhevery what do you think?

**Comment by IgorMinar** [comment] 2016-04-26 04:39
@tbosch, when you said that "we can't just call them" - did you mean that we can't call them because that would sill disqualify them from tree shaking because of possible side effects? or some other reason?

**Comment by IgorMinar** [comment] 2016-04-26 04:41
I also don't see any mention of class field decorators (e.g. `@Input`)

**Comment by martine** [comment] 2016-04-26 14:29
Hmm, identifying which types are references to classes might be hard, but I will take a look.

Re no constructor: just to be clear, you want to add these parameters things to all classes, including the ones with no decorators?

Re inheriting the superclass constructor: if we need to inherit across classes, that means we need to get the type checker involved, because the class we are inheriting from may occur in a different file.  That means we need to compile the whole program once to extract this information.  This is possible but a bit harder.  Maybe it's sufficient to rely on the superclass's definition?

Re your percent pipe example, you wrote `PrecentPipe.parameters = [[PercentPipeConfig, Inject(MySpecialConfig)]];` but in the others you had the `Inject` first -- does the order matter?

**Comment by tbosch** [comment] 2016-04-26 14:48
@martine I updated the proposal at the top with more details and answers to your questions, also including annotations on methods/properties.

**Comment by tbosch** [comment] 2016-04-26 14:52
@IgorMinar I added field/method decorators to the proposal at the top.

We can't just call the decorators as:
1. they don't return the metadata / are no constructor functions for metadata, but rather store the metadata in the global `reflect` store.
2. they are top level function calls which we want to eliminate with this issue.

The confusion might originate because `Component` refers to the decorator, but what we need during runtime is the `ComponentMetadata` instance that is created by the decorator. However, there is no syntactically link between a `Component` decorator and the `ComponentMetadata` that it stores in the global `reflect` store.

**Comment by martine** [comment] 2016-04-26 15:22
@tbosch thanks for clarifying, that looks great.

**Comment by mprobst** [comment] 2016-04-26 15:28
@tbosch the `'Input'` in your example should not be quoted, right?

**Comment by martine** [comment] 2016-04-26 15:30
Another thing that might be helpful is for you to write the types of these various attributes down -- both to clarify what they're doing and also to ensure they make sense.

**Comment by tbosch** [comment] 2016-04-26 15:32
@mprobst yes, thanks for catching (changed it above as well).

**Comment by tbosch** [comment] 2016-04-26 15:37
@martine I added types to the properties as well.

**Comment by martine** [comment] 2016-04-26 16:17
What if the decorator is `@Foo<T1, T2>(...)` -- where do the type arguments T1, T2 go?

**Comment by tbosch** [comment] 2016-04-26 16:38
Let's ignore them for now and add them once we have a good use case that requires them.

**Comment by martine** [comment] 2016-04-26 16:40
What about optional ctor arguments and those with default values?
```
constructor(@Inject foo = bar, baz?: boolean)
```
(the former is hard because we'll again need to get the type checker involved to figure out the type of `bar`).

**Comment by tbosch** [comment] 2016-04-26 16:42
Given the use cases of Angular2:

If there is no explicit type given, let's not record one.
Let's ignore default values.
Let's record optional arguments the same way as non optional arguments for
now.

**Comment by martine** [comment] 2016-04-26 17:44
Let's talk a bit about the types.  You have one where the fields are named:

```js
annotations = [
  {type: Foo, args: [bar, baz]}
]
```

but another where you use an array with a complex type to mix two different kinds of things:

```js
parameters = [
  [Foo, bar, baz]
]
```

Is it intentional?  I'm happy to counterpropose a more consistent approach if you'd like, since I am staring at the code.

**Comment by martine** [comment] 2016-04-26 18:36
My counterproposal is:

```js
interface DecoratorInvocation {
  type: Function;
  args?: any[];
}
static annotations: DecoratorInvocation[]
static parameters: {ctor: new (...args) => any, annotations: DecoratorInvocation[]}[]
static propMetadata: {[key: string]: DecoratorInvocation[]}
```

I'm not sure about the type of that `DecoratorInvocation` thing -- I'm still not quite sure how exactly decorators work.  But it typechecks in my test cases.

**Comment by martine** [comment] 2016-04-26 18:37
Please take another look through the test cases at https://reviews.angular.io/D84 , to ensure the behavior is what you expect.

**Comment by tbosch** [comment] 2016-04-26 20:20
@martine I left some comments. Agree with the better typing for `parameters`

**Comment by tbosch** [comment] 2016-04-26 20:25
Also updated the description above.

**Comment by martine** [comment] 2016-04-27 17:13
So I landed the stuff in sickle.  How else can I help?  Does this need to integrate into the angular build process somewhere?  Or do we need a sickle flag to enable it via the sickle command-line?  Or is this not on the critical path and I should just leave you to it?

**Comment by alexeagle** [comment] 2016-04-27 21:14
Discussed in our meeting: Evan will release to npm and I'll wire into our
CompilerHost.

**Comment by martine** [comment] 2016-05-05 20:53
Closing this since it seems to have worked(?).  Feel free to can open bugs for specific remaining issues if anything.

**Closed by martine** 2016-05-05 20:53 UTC

**Comment by alexeagle** [comment] 2016-05-06 07:23
Yes, we have launched it for some minimal example apps at ngconf and it
does work. Thanks!
I have had fun watching people's expressions when we explain that
Decorators were not tree-shakable so we down-level them ourselves before
handing to TS. People think we are nuts/geniuses/both. :)
