### ISSUE TITLE
Duplicate comments being generated

### ISSUE THREAD

**Issue by devversion** [angular/tsickle#943] opened 2018-11-16 17:14 UTC
Hey there,

**What's the issue?**

Currently enabling closure annotation for a project that uses `NGC`, means that there will be multi-line comments which are duplicated in the JavaScript output.

_https://github.com/angular/cdk-builds/blob/master/esm5/drag-drop.es5.js#L134-L145_

<img src="https://user-images.githubusercontent.com/4987015/48636267-b8545400-e9ca-11e8-8ad4-b231a4163ec5.png" height="300px">

**How can you reproduce the issue**

1. Clone the Angular Material repository (`git clone https://github.com/angular/material2.git`)
2. Run `yarn install`
3. Run `yarn gulp cdk:build`
4. Inspect `dist/packages/cdk/esm5/drag-drop/drag.js` (**note that it needs to ES5 output**)
5. search for: e.g. `CdkDrag.prototype._createPlaceholderElement`

**Additional notes**:

Obviously, this also seems to happen for downleveled `getters` and `setters`.

```js
 Object.defineProperty(CdkDrag.prototype, "disabled", {
        /** Whether starting to drag this element is disabled. */
        get: /**
         * Whether starting to drag this element is disabled.
         * @return {?}
         */
        function () {
            return this._disabled || (this.dropContainer && this.dropContainer.disabled);
        },
...
```

cc/ @jelbourn

**Comment by DevVersion** [comment] 2018-11-16 17:15
Probably related to #637

**Comment by mprobst** [comment] 2018-11-16 17:51
What versions are you using of tsickle and TypeScript? I cannot reproduce:

```
   /**
    * Adds a drag item instance to the registry.
    * @param {I} drag
    * @return {void}
    */
   registerDragItem(drag) {
       this._dragInstances.add(drag);
...
```

Similarly for the ES5 version (without types in our setup):

```
/** Adds a drag item instance to the registry. */
DragDropRegistry.prototype.registerDragItem = function (drag) {
    var _this = this;
    this._dragInstances.add(drag);
    // The `touchmove` event gets bound once, ahead of time, because WebKit
    ...
```

**Comment by DevVersion** [comment] 2018-11-16 18:11
@mprobst Hmm. We currently use tsickle **`v0.32.1`** for building Angular Material. But upgrading to the latest version of `tsickle` didn't help either (from the state of yesterday).

I'm confused that it doesn't happen for you. We also can see them in our build output that is pushed to Github.  See:

* https://github.com/angular/cdk-builds/blob/master/esm5/drag-drop.es5.js#L248-L253
* https://github.com/angular/cdk-builds/blob/master/esm5/drag-drop.es5.js#L738-L744

Also, I see that there has been a release today, so I will check that one out, and let you know.

**Comment by mprobst** [comment] 2018-11-16 18:34
What's your TypeScript version?

**Comment by DevVersion** [comment] 2018-11-16 18:39
* TypeScript: `3.1.1`
* Compiler-CLI: `7.0.3`

Sorry if I forgot any crucial information. All of our dependencies are locked, and the CI therefore just uses what's explicitly specified in the `package.json` of Material

**Comment by mprobst** [comment] 2018-11-19 08:47
@DevVersion I think we landed some patches in TypeScript 3.1.x that fix certain aspects of comment emit. Can you give it a spin with TS 3.1.6, but also TS 3.2.0-rc? At least 3.2.x should have the comment-deduplication fixes.

**Comment by DevVersion** [comment] 2018-11-19 16:39
@mprobst I've tried `3.1.6` and `3.2.0-rc` and it still seems to happen. I can try to create a more isolated demo that we could work with. I'm sure the `Material` repository is not very good as a reproduction.

Also I don't see anything in regards to comments in the TypeScript repository marked as `fixed`. Thanks for looking into this!

**Comment by mprobst** [comment] 2018-11-19 16:54
It's this commit:
https://github.com/Microsoft/TypeScript/pull/25604/commits/a7224ec612d7256a84692f534eb4d763219e4c67

Merged in this commit:
https://github.com/Microsoft/TypeScript/commit/fd2eb4918d7724ae5f6e09d581a9507eb8c63ffc

It's also in 3.1.1 though, so I'm not sure what's going on there.

**Comment by DevVersion** [comment] 2018-11-19 16:57
Ah nice, the PR looks very related to the overall issue, but apparently doesn't seem to fix it.

**Comment by evmar** [comment] 2019-09-17 00:54
I think this is now fixed.

**Closed by evmar** 2019-09-17 00:54 UTC
