### ISSUE TITLE
`goog.forwardDeclare` uses incorrect module names

### ISSUE THREAD

**Issue by jvilk** [angular/tsickle#747] opened 2018-02-15 17:20 UTC
`goog.forwardDeclare` seems to refer to modules using names generated from the *source path*, while modules compiled with tsickle are assigned module names from the *build path*, causing the following Closure compiler error:

```
$ java -jar closure-compiler-v20180204.jar --js build
build/bar.js:8: ERROR - Required namespace "src.foo" never defined.
var tsickle_forward_declare_1 = goog.forwardDeclare("src.foo");
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

build/foo.js:3: ERROR - Required namespace "build.bar" not provided yet.
var bar_1 = goog.require('build.bar');
            ^^^^^^^^^^^^^^^^^^^^^^^^^

2 error(s), 0 warning(s)
```

[Here's a tiny example project that exhibits this failure](https://github.com/jvilk/tsickle-forward-decl-bug), which you can feel free to adopt as a test case if it's useful. You can see the issue [in build/bar.js](https://github.com/jvilk/tsickle-forward-decl-bug/blob/master/build/bar.js#L8).

If I'm doing something totally wrong, let me know.

**Comment by evmar** [comment] 2018-02-15 18:09
Thanks for the excellent bug report.  I think we've had a bunch of bugs around source path vs build path because we don't use this feature in our internal environment.

This bug is probably relevant: https://github.com/angular/tsickle/issues/481

**Comment by mprobst** [comment] 2018-05-28 15:02
Oren: it's a question of build setup. tsickle must generate names for modules in several contexts. Depending on how you configure the build, it might get the path segments wrong.

And yes, this is indeed a duplicate of #481.

**Closed by mprobst** 2018-05-28 15:02 UTC

**Comment by orenmizr** [comment] 2018-05-28 15:09
i simply have a simple **App.ts** that import another moudle. i run tsickle and closure so i do not understand what context are you talking about. 

i am just trying to understand how is it that this package seem to work for a selected few. cause maybe i can get it to work for me too. 

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "outDir": "./build",
    "noEmitHelpers": false
  },
  "include": [
      "src/**/*"
  ],
}
```

**Comment by mprobst** [comment] 2018-05-28 15:55
The problem is that tsickle sees your source files as `src/App.ts`, which
means it creates module names like `src.App`, and not just `App`. You might
have luck by setting a base directory in your tsconfig. but in general this
problem has not been solved I'm afraid.

>

**Comment by orenmizr** [comment] 2018-05-28 16:18
did not work. i got a simple test case. no logic - just imports.  test case: https://www.dropbox.com/s/1xrm4jmxumdiad5/App.zip?dl=0

i really want to get around this - if you can help

**Comment by orenmizr** [comment] 2018-05-29 11:18
ALSO: 

```
var Utils_1 = goog.require('Utils');
const tsickle_forward_declare_1 = goog.forwardDeclare("Utils");
const tsickle_forward_declare_2 = goog.forwardDeclare("IContext");
goog.require("IContext"); // force type-only module to be loaded
```

IContext is a type. tsickle output has require for it - but there is no js since it is just a type. 

```
build/App.js:9: ERROR - Required namespace "IContext" never defined.
const tsickle_forward_declare_2 = goog.forwardDeclare("IContext");
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

build/App.js:10: ERROR - Required namespace "IContext" never defined.
goog.require("IContext"); // force type-only module to be loaded
^^^^^^^^^^^^^^^^^^^^^^^^
```
